name: Deploy Python Web App to AWS EC2 instance

on:
  push:
    branches:
      - main
      - staging
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest --junitxml=test-results.xml

  deploy-staging:
    needs: build
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    steps:
      - name: SSH into STAGING host and Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAG_SSH_PRIV_KEY }}
          script: |
            cd GithubAction-Python
            git pull origin staging
            pip install -r requirements.txt
            nohup python3 app.py > app.log 2>&1 &

  deploy-production:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: SSH into PROD host and Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_PRIV_KEY }}
          script: |
            cd GithubAction-Python
            git pull origin main
            pip install -r requirements.txt
            nohup python3 app.py > app.log 2>&1 &
