name: Deploy Python Web App to AWS EC2 instance

on:
  push:
    branches:
      - main
      - staging
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: pytest --junitxml=test-results.xml

      - name: Build  # This step is now explicit (good practice)
        if: steps.Run_Tests.outcome == 'success'  # Only build if tests pass
        run: echo "Building the application..." # Replace with your actual build commands
        # ... your build steps here ...

  deploy-staging:
    needs: build  # Correct dependency
    if: github.ref == 'refs/heads/staging' && needs.build.outcome == 'success' # Correct conditional and dependency
    runs-on: ubuntu-latest
    environment: staging # Add environment context
    steps:
      - name: Checkout Code # Add checkout step
        uses: actions/checkout@v3

      - name: SSH into STAGING host and Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAG_SSH_PRIV_KEY }}
          script: |
            cd GithubAction-Python
            git pull origin staging
            pip install -r requirements.txt
            nohup python3 app.py > app.log 2>&1 &

  deploy-production:
    needs: build  # Correct dependency
    if: startsWith(github.ref, 'refs/tags/') && needs.build.outcome == 'success' # Correct conditional and dependency
    runs-on: ubuntu-latest
    environment: production # Add environment context
    steps:
      - name: Checkout Code # Add checkout step
        uses: actions/checkout@v3

      - name: SSH into PROD host and Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_PRIV_KEY }}
          script: |
            cd GithubAction-Python
            git pull origin main
            pip install -r requirements.txt
            nohup python3 app.py > app.log 2>&1 &
